# Site
name: 'AstroSpaceTech'
description: 'This blog will brings you to enlighten mainly about Astronomy(Cosmology), Aerospace engineering and Technology✌'
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.ico"
baseurl: '/'
disqus: 'astrospacetech'
email: 'admin@astrospacetech.in'
mailchimp-list: 'https://astrospacetech.us4.list-manage.com/subscribe/post?u=3f09cf1bc456c7a0f07406116&amp;id=db468df3cc'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    AstromuonKuki:
      name: AstromuonKuki
      site: https://blog.astrospacetech.in
      avatar: ../assets/images/avatars/AstroMuonKuki.jpg
      bio: CEO of Astrospacetech.in, Aerospace Engineer, Writer, and an aspiring Astronomer.
      email: kuki@astrospacetech.in
      youtube: https://www.youtube.com/channel/UC7GqCFeK4-9yo_CsXmckIxQ
      facebook: https://facebook.com/AstroSpaceTech/

    XinYaanZyoy:
      name: XinYaanZyoy
      site: https://XinYaanZyoy.github.io
      avatar: ../assets/images/avatars/XinYaanZyoy.png
      bio: CTO of astrospacetech.in, an Explorer of information, and a metaphysicist!
      email: tech@astrospacetech.in
      twitter: https://twitter.com/XinYaanZyoy
      github: https://github.com/XinYaanZyoy
      facebook: https://facebook.com/49yatriyaan.love

    AstroSpaceTech:
      name: AstroSpaceTech
      site: "/"
      avatar: ../assets/images/logo.png
      bio: the Astrospacetech.in, admin!
      email: admin@astrospacetech.in
      instagram: https://instagram.com/astrospacetech
      facebook: https://facebook.com/AstroSpaceTech.in
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: AstroSpaceTech
      avatar: /assets/images/logo.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 8



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
