name: 'AstroSpaceTech'
description: "AstroSpaceTech is an international platform for various STEM students mainly focus only on Astronomy, Aerospace engineering and Technology.The goal is to give best gateway for the next humanity, brings down space objects on Earth, build our own rockets and contribute our innovator ideas for the development of human civilization.Currently, we are doing research on our domains and exchanging our ideas through online platform."
logo: "../assets/images/logo.png"
favicon: "../assets/images/favicon.ico"
baseurl: ''
disqus: 'astrospacetech'
email: 'admin@astrospacetech.in'
mailchimp-list: 'https://astrospacetech.us4.list-manage.com/subscribe/post?u=3f09cf1bc456c7a0f07406116&amp;id=db468df3cc'

include: ["_pages"]
permalink: /:title/

plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

team:
    AstromuonKuki:
      name: AstromuonKuki
      site: https://blog.astrospacetech.in
      avatar: ../assets/images/avatars/AstroMuonKuki.jpg
      bio: CEO & Founder of Astrospacetech.in, Student of Aerospace Engineering, Writer, and amateur Astronomer. <br> Manipur(North-East), 🇮🇳 India.
      email: kuki@astrospacetech.in
      youtube: https://www.youtube.com/channel/UC7GqCFeK4-9yo_CsXmckIxQ
      facebook: https://facebook.com/AstroSpaceTech/
      linkedIn: https://www.linkedin.com/in/astromuon-kuki-9a7121156
      whatsapp: +918787405917
    BrianBlasius:
      name: Brian Blasius
      avatar: ../assets/images/avatars/brian.jpg
      bio: Student of Mechatronics. <br> Malindi, 🇰🇪 Kenya.
      email: einsteinblasius@gmail.com
    Norbu:
      name: Kinley Norbu
      avatar: ../assets/images/avatars/norbu.jpg
      bio:  Drilling engineer; Department of Geology and Mine Under Ministry of Economic Affairs(Bhutan), and degree in Mechatronics Engineer, 🇧🇹 Bhutan.
      email: drogpo.nk@gmail.com
    RavikantDohre:
      name: Ravikant Dohre
      avatar: ../assets/images/avatars/RavikantDohre.jpg
      bio: Student of Aerospace Engineering, MP, india
    Anudeep:
      name: Anudeep
      avatar: ../assets/images/avatars/anudeep.jpg
      bio: Student of Mechanical and Automation Engineering. <br> Rajasthaan, 🇮🇳 India.
      email: meharanudeep.183@gmail.com
    AvinabaMajumdar:
      name: AvinabaMajumdar
      avatar: ../assets/images/avatars/Alex.jpg
      bio: Junior Researcher at the New-York Academy of sciences. <br> West Bengal, 🇮🇳 India.
      email: avinaba.wtms@gmail.com
    MangHaokip:
      name: Mang Haokip
      avatar: ../assets/images/avatars/MangHaokip.jpg
      bio: Master in geology at IIT(ISM)
    MineoKhongsai:
      name: Mineo Khongsai
      avatar: ../assets/images/avatars/MineoKhongsai.jpg
      bio: Content Designer
    Ganesh:
      name: Ganesh
      avatar: ../assets/images/avatars/Ganesh.jpg
      bio: Market Analysis and Product Developement

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      author: AstroSpaceTech
      avatar: /assets/images/logo.png
      
  - scope:
      path: "_pages"
    values:
      layout: page
      
markdown: kramdown
highlighter: rouge

paginate: 10

exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
