name: 'AstroSpaceTech'
description: 'This blog will brings you to enlighten mainly about Astronomy(Cosmology), Aerospace engineering and Technology✌'
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.ico"
baseurl: '/'
disqus: 'astrospacetech'
email: 'admin@astrospacetech.in'
mailchimp-list: 'https://astrospacetech.us4.list-manage.com/subscribe/post?u=3f09cf1bc456c7a0f07406116&amp;id=db468df3cc'

include: ["_pages"]
permalink: /:title/

plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
teams:
    Astro:
      name: Astronomy Team
      avatar: ../assets/images/avatars/astro.jpg
      details: this is astro team
      members:
        - AstromuonKuki
        - Anudeep
        - AvinabaMajumdar
    Space:
      name: SpaceScience Team
      avatar: ../assets/images/avatars/spacescience.jpg
      details: this is space science team
      members:
        - XinYaanZyoy
        - AstromuonKuki
    Tech:
      name: Technology team
      avatar: ../assets/images/avatars/tech.jpg
      details: this is technology team
      members:
        - XinYaanZyoy
        - BrianBlasius
  
authors:
    AstromuonKuki:
      name: AstromuonKuki
      site: https://blog.astrospacetech.in
      avatar: ../assets/images/avatars/AstroMuonKuki.jpg
      bio: CEO of Astrospacetech.in, Aerospace Engineer, Writer, and an aspiring Astronomer.
      email: kuki@astrospacetech.in
      youtube: https://www.youtube.com/channel/UC7GqCFeK4-9yo_CsXmckIxQ
      facebook: https://facebook.com/AstroSpaceTech/

    XinYaanZyoy:
      name: XinYaanZyoy
      site: https://XinYaanZyoy.github.io
      avatar: ../assets/images/avatars/XinYaanZyoy.png
      bio: CTO of astrospacetech.in, an Explorer of information, and a metaphysicist!
      email: tech@astrospacetech.in
      twitter: https://twitter.com/XinYaanZyoy
      github: https://github.com/XinYaanZyoy
      facebook: https://facebook.com/49yatriyaan.love
      instagram: https://instagram.com/49yatriyaan.love

    AstroSpaceTech:
      name: AstroSpaceTech
      site: "/"
      avatar: ../assets/images/logo.png
      bio: the Astrospacetech.in, admin!
      email: admin@astrospacetech.in
      instagram: https://instagram.com/astrospacetech
      facebook: https://facebook.com/AstroSpaceTech.in
      
members:
    AstromuonKuki:
      name: AstromuonKuki
      site: https://blog.astrospacetech.in
      avatar: ../assets/images/avatars/AstroMuonKuki.jpg
      bio: CEO of Astrospacetech.in, Aerospace Engineer, Writer, and an aspiring Astronomer.
      email: kuki@astrospacetech.in
      youtube: https://www.youtube.com/channel/UC7GqCFeK4-9yo_CsXmckIxQ
      facebook: https://facebook.com/AstroSpaceTech/
    
    XinYaanZyoy:
      name: XinYaanZyoy
      site: https://XinYaanZyoy.github.io
      avatar: ../assets/images/avatars/XinYaanZyoy.png
      bio: CTO of astrospacetech.in, an Explorer of information, and a metaphysicist!
      email: tech@astrospacetech.in
      twitter: https://twitter.com/XinYaanZyoy
      github: https://github.com/XinYaanZyoy
      facebook: https://facebook.com/49yatriyaan.love
      instagram: https://instagram.com/49yatriyaan.love
    
    BrianBlasius:
      name: Brian Blasius
      avatar: ../assets/images/avatars/brian.jpeg
      bio: I wish to make smart engineered systems  that can be used to help humanity, in earth and beyond.
      email: einsteinblasius@gmail.com
    
    Anudeep:
      name: Anudeep
      avatar: ../assets/images/avatars/anudeep.jpeg
      bio: I'm pursuing my B.Tech in Mechanical and Automation Engineering(final year) from Amity University
      email: meharanudeep.183@gmail.com
    
    AvinabaMajumdar:
      name: AvinabaMajumdar
      avatar: ../assets/images/avatars/Alex.jpeg
      bio: Research at the New-York acedamy of sciences
      email: avinaba.wtms@gmail.com

defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
      author: AstroSpaceTech
      avatar: /assets/images/logo.png
      
  - scope:
      path: "_pages"
    values:
      layout: page
      
markdown: kramdown
highlighter: rouge

paginate: 8

exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
