version: 2
jobs:
  new_post:
    machine: true
    steps:
      - checkout
      - run:
          name: runnning transformation script
          command: make transform
workflows:
  version: 2
  build:
    jobs:
      - new_post
