version: 2
jobs:
  new_post:
    machine:
      image: ubuntu-1904
    steps:
      - run:
          name: runnning transformation script
          command: make transform
workflows:
  version: 2
  build:
    jobs:
      - new_post
